// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBng86quaTuC38VV5nWhwyrB05bXNsN0gw',
    appId: '1:662929013582:web:3cb65967eaa3ea249cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    authDomain: 'abdulrahmanabusnena-70718.firebaseapp.com',
    databaseURL: 'https://abdulrahmanabusnena-70718-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abdulrahmanabusnena-70718.firebasestorage.app',
    measurementId: 'G-CRT5WLDCKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmkyEHYEuKGeNcHet-QMk0fj8OvyBBcX4',
    appId: '1:662929013582:android:700409db79b5d9cf9cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    databaseURL: 'https://abdulrahmanabusnena-70718-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abdulrahmanabusnena-70718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDmiN1MxVO0YI4Dwu6GoQPivVvfwQZis',
    appId: '1:662929013582:ios:f9f9eb66c718cd4d9cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    databaseURL: 'https://abdulrahmanabusnena-70718-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abdulrahmanabusnena-70718.firebasestorage.app',
    iosBundleId: 'com.example.eTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDmiN1MxVO0YI4Dwu6GoQPivVvfwQZis',
    appId: '1:662929013582:ios:f9f9eb66c718cd4d9cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    databaseURL: 'https://abdulrahmanabusnena-70718-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abdulrahmanabusnena-70718.firebasestorage.app',
    iosBundleId: 'com.example.eTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBng86quaTuC38VV5nWhwyrB05bXNsN0gw',
    appId: '1:662929013582:web:b6dd355d3483f7bf9cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    authDomain: 'abdulrahmanabusnena-70718.firebaseapp.com',
    databaseURL: 'https://abdulrahmanabusnena-70718-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'abdulrahmanabusnena-70718.firebasestorage.app',
    measurementId: 'G-P3M08JWC70',
  );
}
